### ISSUE TITLE
Algorithm to identify similar frames in a video?

### ISSUE THREAD

**Issue by Mintxr** [chi0tzp/PyVideoFramesExtractor#3]
I was looking for an AI/algorithm to identify an almost exact copy of the frame I chose. I heard OpenCV is good but I literally do not have the time to do so. Are any programs that already do this?

**Comment by chi0tzp** [comment]
Sorry, I can't help you. Believe it or not, I also do not have the time to do so, literally. Closing as irrelevant to the repo.
