### ISSUE TITLE
NameError: name 'args_' is not defined

### ISSUE THREAD

**Issue by aqpre890** [chi0tzp/PyVideoFramesExtractor#4]
I just tried it with your demo data, but an error occurred.
NameError: name 'args_' is not defined
Why does this error occur?

**Comment by chi0tzp** [comment]
@aqpre890 I just tested the demo and it works just fine. I'd suggest installing the required packages using python's native virtual environment (see the updated readme) and then trying again.

**Comment by aqpre890** [comment]
> @aqpre890 I just tested the demo and it works just fine. I'd suggest installing the required packages using python's native virtual environment (see the updated readme) and then trying again.

Thank you. It works well when I run it in Linux.
